#!/usr/bin/env php
<?php

// Include autoloader
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Scara\Console\Console;

$app = new Application();

// Register commands
$console = new Console();

// Holds all commands defined in array
$commands = [
    // database commands
    'database' => [
        'migrate',
        'MigrationBuilder',
        'rollback',
        'reset',
        'truncate',
        'delete',
        'seed',
        'model',
    ],
    'ClearCache',
    // controller commands
    'controller' => [
        'CreateController',
        'DeleteController',
    ],
    'ConfigPublish',
];

// Loop through commands array and register each command
foreach($commands as $key => $value) {
    if(is_array($value)) {
        foreach($value as $command) {
            $app->add($console->register($key.'/'.$command));
        }
    }
    else {
        $app->add($console->register($value));
    }
}

$app->run();
